opponentModeAllowed: true
icon: mom
difficulties:
  - easy
  - normal
  - hard
ratings:
  easy: 2
  normal: 3
  hard: 4
color: "#FC96D7"
coopAllowed: true
stepsPerBeat: 4
displayName: M.I.L.F
beatsPerMeasure: 4
needsVoices: true
bpm: 180
album: volume1