opponentModeAllowed: true
icon: spooky
difficulties:
  - easy
  - normal
  - hard
ratings:
  easy: 1
  normal: 1
  hard: 2
color: "#223344"
coopAllowed: true
stepsPerBeat: 4
displayName: Spookeez
beatsPerMeasure: 4
needsVoices: true
bpm: 150
