opponentModeAllowed: true
icon: parents-christmas
difficulties:
  - easy
  - normal
  - hard
ratings:
  easy: 1
  normal: 2
  hard: 3
gradient: ["#A0D1FF", "#7777FF"]
coopAllowed: true
stepsPerBeat: 4
displayName: Eggnog
beatsPerMeasure: 4
needsVoices: true
bpm: 150
album: volume1
freeplayCapsule: mall