opponentModeAllowed: true
icon: mom
difficulties:
  - easy
  - normal
  - hard
ratings:
  easy: 1
  normal: 2
  hard: 2
color: "#FC96D7"
coopAllowed: true
stepsPerBeat: 4
displayName: Satin Panties
beatsPerMeasure: 4
needsVoices: true
bpm: 110
album: volume1