customValues: {}
gradient: ["#E40F3D", "#E72EFF"]
opponentModeAllowed: true
icon: gf
difficulties:
  - easy
  - normal
  - hard
ratings:
  easy: 0
  normal: 0
  hard: 1
coopAllowed: true
stepsPerBeat: 4
displayName: Tutorial
needsVoices: false
beatsPerMeasure: 4
bpm: 100
