name: Test Builds

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:

  windows:
    permissions: write-all
    runs-on: windows-latest

    steps:
      - name: Checking Latest Commit
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Run Cache
        uses: actions/cache@v4.3.0
        with:
          # not caching the bin folder to prevent asset duplication and stuff like that
          key: windows-build-cache
          path: |
            .haxelib/
            export/build/windows/haxe/
            export/build/windows/obj/
          restore-keys: windows-build-cache

      - name: Run Setup
        run: .\".github\libs.bat"

      - name: Building HXCPP
        run: |
          cd ./.haxelib/hxcpp/git/tools/hxcpp
          haxe compile.hxml
          cd ../../../../../

      - name: Compile Engine
        run: haxelib run lime build windows -final -Daction -Dbranch-main

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: Violet Windows Build
          path: export/build/windows/bin
          overwrite: true
          include-hidden-files: true
          if-no-files-found: error

      - name: Clearing Cache
        uses: actions/github-script@v6
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              if (cache.key == 'windows-build-cache') {
                console.log('Clearing ' + cache.key + '...')
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })
                console.log('Cache cleared.')
              }
            }

      - name: Run New Cache
        uses: actions/cache@v4.3.0
        with:
          # not caching the bin folder to prevent asset duplication and stuff like that
          key: windows-build-cache
          path: |
            .haxelib/
            export/build/windows/haxe/
            export/build/windows/obj/
          restore-keys: windows-build-cache

  linux:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checking Latest Commit
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Run Cache
        uses: actions/cache@v4.3.0
        with:
          key: linux-build-cache
          path: |
            .haxelib/
            export/build/linux/haxe/
            export/build/linux/obj/
          restore-keys: linux-build-cache

      - name: Run Setup
        run: bash .github/libs.sh

      - name: Install VLC (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y libvlc-dev libvlccore-dev

      - name: Building HXCPP
        run: |
          cd ./.haxelib/hxcpp/git/tools/hxcpp
          haxe compile.hxml
          cd ../../../../../

      - name: Compile Engine
        run: haxelib run lime build linux -final -Daction -Dbranch-main

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: Violet Linux Build
          path: export/build/linux/bin
          overwrite: true
          include-hidden-files: true
          if-no-files-found: error

      - name: Clearing Cache
        uses: actions/github-script@v6
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              if (cache.key == 'linux-build-cache') {
                console.log('Clearing ' + cache.key + '...')
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })
                console.log('Cache cleared.')
              }
            }

      - name: Run New Cache
        uses: actions/cache@v4.3.0
        with:
          key: linux-build-cache
          path: |
            .haxelib/
            export/build/linux/haxe/
            export/build/linux/obj/
          restore-keys: linux-build-cache

  macos:
    permissions: write-all
    runs-on: macos-latest

    steps:
      - name: Checking Latest Commit
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Run Cache
        uses: actions/cache@v4.3.0
        with:
          key: mac-build-cache
          path: |
            .haxelib/
            export/build/macos/haxe/
            export/build/macos/obj/
          restore-keys: mac-build-cache

      - name: Run Setup
        run: bash .github/libs.sh

      - name: Install VLC (macOS)
        run: |
          brew update
          brew install --cask vlc

      - name: Building HXCPP
        run: |
          cd ./.haxelib/hxcpp/git/tools/hxcpp
          haxe compile.hxml
          cd ../../../../../

      - name: Compile Engine
        run: haxelib run lime build mac -final -Daction -Dbranch-main

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: Violet macOS Build
          path: export/build/macos/**
          overwrite: true
          include-hidden-files: true
          if-no-files-found: error

      - name: Clearing Cache
        uses: actions/github-script@v6
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              if (cache.key == 'mac-build-cache') {
                console.log('Clearing ' + cache.key + '...')
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })
                console.log('Cache cleared.')
              }
            }

      - name: Run New Cache
        uses: actions/cache@v4.3.0
        with:
          key: mac-build-cache
          path: |
            .haxelib/
            export/build/macos/haxe/
            export/build/macos/obj/
          restore-keys: mac-build-cache
