opponentModeAllowed: true
icon: tankman
difficulties:
  - easy
  - normal
  - hard
ratings:
  easy: 2
  normal: 3
  hard: 4
gradient: ["#F6B604", "#FFFFFF"]
freeplayCapsule: battlefield
coopAllowed: true
stepsPerBeat: 4
displayName: Ugh
beatsPerMeasure: 4
needsVoices: true
bpm: 160
album: volume2
